# Generated by Django 6.1 on 2026-08-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=100)),
                ('toge', models.BooleanField(default=False)),
                ('echarpe', models.BooleanField(default=False)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
