# Generated by Django 6.1 on 2026-08-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_financialadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='frais_soutenance',
            field=models.BooleanField(default=False),
        ),
    ]
