# Generated by Django 6.1 on 2026-09-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_studentregistration_frais_soutenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='academic_supervisor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='professional_supervisor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='theme',
            field=models.TextField(blank=True, default=''),
        ),
    ]
