# Generated by Django 6.1 on 2026-09-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_studentregistration_academic_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='filiere',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='niveau',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
