# Generated by Django 6.1 on 2026-09-30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_alter_studentregistration_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyerPaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('flyer_png', models.BinaryField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('initiating', 'Initiating'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=16)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('payment_method', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
