# Generated by Django 6.1 on 2026-10-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_flyerpaymentorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyerpaymentorder',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('initiating', 'Initiating'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='created', max_length=16),
        ),
    ]
