# Generated by Django 6.1 on 2026-10-07 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_alter_flyerpaymentorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyerAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_digest', models.CharField(max_length=64, unique=True)),
                ('code_hint', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_flyer_access_codes', to=settings.AUTH_USER_MODEL)),
                ('redeemed_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_access_code', to='generator.flyerpaymentorder')),
            ],
        ),
    ]
